version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tree_of_life
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: /wait-for-it.sh db:5432 -- uvicorn backend.main:app --host 0.0.0.0 --port 8080 --reload
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules # avoid overwriting node_modules
  #   depends_on:
  #     - backend

  # frontend service will be added here later

volumes:
  postgres_data:
