version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tree_of_life
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: benmotevalli/tree-of-life:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRE_URL=postgresql+asyncpg://postgres:postgres@db:5432/tree_of_life
      - SECRET=your-super-secret-key
      - DEBUG=True
      - ORIGINS=["http://localhost:4200"]
      - API_PRE_PATH='/api'
      - EMBED_UI=True
    depends_on:
      - db
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ./backend/.env
  #     # Add other production environment variables here
  #   depends_on:
  #     - db

volumes:
  postgres_data:
