"""added question_group table.

Revision ID: 24e75e3f8179
Revises: a8afb6d0af19
Create Date: 2025-06-04 14:03:27.258470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e75e3f8179'
down_revision: Union[str, None] = 'a8afb6d0af19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('example_answer', sa.String(), nullable=True))
    op.add_column('question', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'question', 'question_group', ['group_id'], ['id'])
    op.add_column('user_timetable', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_timetable', 'title')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'group_id')
    op.drop_column('question', 'example_answer')
    # ### end Alembic commands ###
