"""some restructuring.

Revision ID: 3ef6b03c7480
Revises: a34750c0fe46
Create Date: 2025-06-05 11:12:30.368193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef6b03c7480'
down_revision: Union[str, None] = 'a34750c0fe46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_tag_association', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('question_tag_association', 'tag_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_tag_association', 'tag_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('question_tag_association', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
