"""adding two columns to timetable table

Revision ID: ad40bb1f54aa
Revises: 3ef6b03c7480
Create Date: 2025-06-06 13:53:55.132478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad40bb1f54aa'
down_revision: Union[str, None] = '3ef6b03c7480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_timetable', sa.Column('is_submitted', sa.String(), nullable=False))
    op.add_column('user_timetable', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_timetable', 'notes')
    op.drop_column('user_timetable', 'is_submitted')
    # ### end Alembic commands ###
