"""user_timetables: fixed is_submitted to boolean.

Revision ID: e3715fa9faa4
Revises: cf7065fef486
Create Date: 2025-06-08 02:38:12.508174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3715fa9faa4'
down_revision: Union[str, None] = 'cf7065fef486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column(
        'user_timetable',
        'is_submitted',
        existing_type=sa.String(),
        type_=sa.Boolean(),
        nullable=False,
        postgresql_using="is_submitted::boolean"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_timetable', 'is_submitted',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
