"""user_answers: removed date_of_plan column.

Revision ID: eaac9cfaea71
Revises: e3715fa9faa4
Create Date: 2025-06-08 12:01:11.950005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaac9cfaea71'
down_revision: Union[str, None] = 'e3715fa9faa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answer', 'date_of_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer', sa.Column('date_of_plan', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
